# Generated by Django 5.0.6 on 2024-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_location', models.CharField(max_length=20)),
                ('course_department', models.CharField(max_length=20)),
                ('course_description', models.CharField(max_length=100)),
                ('course_level', models.CharField(max_length=20)),
                ('course_capacity', models.PositiveBigIntegerField()),
                ('course_duration', models.DurationField()),
                ('course_trainer', models.PositiveSmallIntegerField()),
                ('course_code', models.PositiveSmallIntegerField()),
                ('course_price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
