# Generated by Django 5.0.6 on 2024-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.DecimalField(decimal_places=2, default='1000000.00', max_digits=8),
        ),
    ]
