# Generated by Django 5.0.6 on 2024-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('course', models.CharField(max_length=200)),
                ('classroom', models.CharField(max_length=50)),
                ('dayoftheweek', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('syllabus', models.TextField()),
                ('capacity', models.IntegerField()),
                ('attendance', models.IntegerField()),
            ],
        ),
    ]
