# Generated by Django 5.0.6 on 2024-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('capacity', models.PositiveIntegerField()),
                ('materials', models.TextField()),
                ('schedule', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('resources', models.TextField()),
                ('students', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
