# Generated by Django 5.0.6 on 2024-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='schedule',
            field=models.DateTimeField(),
        ),
    ]
