# Generated by Django 5.0.6 on 2024-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_class_name_alter_class_schedule'),
        ('student', '0003_remove_student_course_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
