# Generated by Django 5.0.6 on 2024-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(default='default_bio_value', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='default_course_value', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='default_gender_value', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='default_guardian_name_value', max_length=50),
        ),
    ]
